# springdoc-openapi项目访问访问地址: http://127.0.0.1:8080/doc.html
springdoc:
  swagger-ui:
    # path: 配置swagger-ui.html/UI界面的访问路径,默认为/swagger-ui.html
    path: /swagger-ui.html
    # tags-sorter: 接口文档中的tags排序规则,默认为alpha,可选值为alpha(按字母顺序排序)或as-is(按照在代码中定义的顺序排序)
    tags-sorter: alpha
    operations-sorter: alpha

  api-docs:
    # path: 配置api-docs的访问路径,默认为/v3/api-docs
    path: /v3/api-docs

# group-configs: 配置分组信息
  group-configs:
    # group: 分组名称
    - group: 'default'
      # paths-to-match: 配置要匹配的路径,默认为/**
      paths-to-match: '/**'
      # packages-to-scan: 配置要扫描的包的路径,直接配置为Controller类所在的包名即可
      packages-to-scan: cn.bytewisehub.pai.web

# knife4j项目访问访问地址:http://127.0.0.1:8080/doc.html#/home
knife4j:
  # 设置为true以启用Knife4j增强功能,这将再应用程序中启用Knife4j UI
  enable: true
  setting:
    # language: 设置Knife4j UI的语言,默认为zh_cn,可选值为zh_cn或en
    language: zh_cn
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: thomas # 自己设置一个
    password: thomas666 # 自己设置一个
