# 访问接口
server:
  port: 8080
# Spring配置
spring:
  # 启用指定配置文件
  #（文件名需满足application-{profile}.yml的格式）
  profiles:
    active: druid,email,openapi,redis,secret
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MyBatis Plus 的配置
mybatis-plus:
  # mybatis 配置文件的路径
  # config-location: "classpath:mybatis/mybatis.config"
  # mapper 映射文件的路径，可以有多个
  mapper-locations: classpath:/mapper/**Mapper.xml
  # 指定POJO扫描包来让mybatis自动扫描到自定义的POJO
  type-aliases-package: com.material.entity
material:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${material.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: ${material.jwt.user-secret-key}
    user-ttl: 7200000
    user-token-name: authentication
  cos:
    appid: ${material.cos.appid}
    secret-id: ${material.cos.secret-id}
    secret-key: ${material.cos.secret-key}
    bucket-name: ${material.cos.bucket-name}
    cos-path: ${material.cos.cos-path}
    region-name: ap-${material.cos.region-name}
  wechat:
    appid: ${material.wechat.appid}
    secret: ${material.wechat.secret}